// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckAdb() {
  return window['go']['main']['App']['CheckAdb']();
}

export function CheckNpcap() {
  return window['go']['main']['App']['CheckNpcap']();
}

export function CheckUpdate() {
  return window['go']['main']['App']['CheckUpdate']();
}

export function CreateDb(arg1) {
  return window['go']['main']['App']['CreateDb'](arg1);
}

export function CreateTask(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateTask'](arg1, arg2, arg3, arg4);
}

export function DeleteTask(arg1) {
  return window['go']['main']['App']['DeleteTask'](arg1);
}

export function DeleteTaskReport(arg1) {
  return window['go']['main']['App']['DeleteTaskReport'](arg1);
}

export function DirectFetchLoop(arg1) {
  return window['go']['main']['App']['DirectFetchLoop'](arg1);
}

export function DirectFetchStop() {
  return window['go']['main']['App']['DirectFetchStop']();
}

export function DisableAutoListen() {
  return window['go']['main']['App']['DisableAutoListen']();
}

export function DisableBookData() {
  return window['go']['main']['App']['DisableBookData']();
}

export function DisableCaptureRequests() {
  return window['go']['main']['App']['DisableCaptureRequests']();
}

export function DisableEnemyMonitor() {
  return window['go']['main']['App']['DisableEnemyMonitor']();
}

export function DisableGetBattleReport() {
  return window['go']['main']['App']['DisableGetBattleReport']();
}

export function DisableGetReport() {
  return window['go']['main']['App']['DisableGetReport']();
}

export function EnableAutoListen() {
  return window['go']['main']['App']['EnableAutoListen']();
}

export function EnableBookData() {
  return window['go']['main']['App']['EnableBookData']();
}

export function EnableCaptureRequests() {
  return window['go']['main']['App']['EnableCaptureRequests']();
}

export function EnableEnemyMonitor() {
  return window['go']['main']['App']['EnableEnemyMonitor']();
}

export function EnableGetBattleReport() {
  return window['go']['main']['App']['EnableGetBattleReport']();
}

export function EnableGetReport(arg1, arg2) {
  return window['go']['main']['App']['EnableGetReport'](arg1, arg2);
}

export function ExportAllBattleReports() {
  return window['go']['main']['App']['ExportAllBattleReports']();
}

export function ExportTaskReport(arg1) {
  return window['go']['main']['App']['ExportTaskReport'](arg1);
}

export function GetBattleReports(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['GetBattleReports'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function GetDashboardStats() {
  return window['go']['main']['App']['GetDashboardStats']();
}

export function GetDbList() {
  return window['go']['main']['App']['GetDbList']();
}

export function GetFetchTemplate() {
  return window['go']['main']['App']['GetFetchTemplate']();
}

export function GetGroupWu() {
  return window['go']['main']['App']['GetGroupWu']();
}

export function GetHotRank() {
  return window['go']['main']['App']['GetHotRank']();
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetMemberActivity() {
  return window['go']['main']['App']['GetMemberActivity']();
}

export function GetMyUnionName() {
  return window['go']['main']['App']['GetMyUnionName']();
}

export function GetPlayerTeam(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetPlayerTeam'](arg1, arg2, arg3, arg4);
}

export function GetReportNumByTaskId(arg1) {
  return window['go']['main']['App']['GetReportNumByTaskId'](arg1);
}

export function GetScrollMode() {
  return window['go']['main']['App']['GetScrollMode']();
}

export function GetTask(arg1) {
  return window['go']['main']['App']['GetTask'](arg1);
}

export function GetTaskList() {
  return window['go']['main']['App']['GetTaskList']();
}

export function GetTeamCounter(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetTeamCounter'](arg1, arg2, arg3, arg4);
}

export function GetTeamGroup() {
  return window['go']['main']['App']['GetTeamGroup']();
}

export function GetTeamUser(arg1) {
  return window['go']['main']['App']['GetTeamUser'](arg1);
}

export function GetTeamWinRate(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['GetTeamWinRate'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function GetTeamWinRateByTeam(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['GetTeamWinRateByTeam'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SelectDb(arg1) {
  return window['go']['main']['App']['SelectDb'](arg1);
}

export function SetScrollMode(arg1) {
  return window['go']['main']['App']['SetScrollMode'](arg1);
}

export function StartAutoScroll(arg1, arg2) {
  return window['go']['main']['App']['StartAutoScroll'](arg1, arg2);
}

export function StatisticsReport(arg1) {
  return window['go']['main']['App']['StatisticsReport'](arg1);
}

export function StopAutoScroll() {
  return window['go']['main']['App']['StopAutoScroll']();
}

export function TestDirectFetch() {
  return window['go']['main']['App']['TestDirectFetch']();
}
