// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AiChat(arg1:string):Promise<string>;

export function CheckAdb():Promise<string>;

export function CheckNpcap():Promise<string>;

export function CheckUpdate():Promise<string>;

export function ClearAiChat():Promise<string>;

export function CreateDb(arg1:string):Promise<string>;

export function CreateTask(arg1:string,arg2:number,arg3:Array<string>,arg4:Array<string>):Promise<string>;

export function DeleteTask(arg1:number):Promise<string>;

export function DeleteTaskReport(arg1:number):Promise<string>;

export function DirectFetchLoop(arg1:number):Promise<string>;

export function DirectFetchStop():Promise<string>;

export function DisableAutoListen():Promise<string>;

export function DisableBookData():Promise<string>;

export function DisableCaptureRequests():Promise<string>;

export function DisableEnemyMonitor():Promise<string>;

export function DisableGetBattleReport():Promise<string>;

export function DisableGetReport():Promise<string>;

export function EnableAutoListen():Promise<string>;

export function EnableBookData():Promise<string>;

export function EnableCaptureRequests():Promise<string>;

export function EnableEnemyMonitor():Promise<string>;

export function EnableGetBattleReport():Promise<string>;

export function EnableGetReport(arg1:number,arg2:number):Promise<string>;

export function ExportAllBattleReports():Promise<string>;

export function ExportAllEnemyTeams(arg1:number):Promise<string>;

export function ExportAllMemberTeams(arg1:number):Promise<string>;

export function ExportTaskReport(arg1:number):Promise<string>;

export function GetBattleReportStatus():Promise<string>;

export function GetBattleReports(arg1:string,arg2:number,arg3:number,arg4:string,arg5:number,arg6:number):Promise<string>;

export function GetDashboardStats():Promise<string>;

export function GetDbList():Promise<string>;

export function GetDefeatedEnemyTeams(arg1:number,arg2:number,arg3:number):Promise<string>;

export function GetFetchTemplate():Promise<string>;

export function GetGroupWu():Promise<string>;

export function GetHotRank():Promise<string>;

export function GetLogs():Promise<string>;

export function GetMemberActivity():Promise<string>;

export function GetMyUnionName():Promise<string>;

export function GetPlayerTeam(arg1:string,arg2:string,arg3:number,arg4:number):Promise<string>;

export function GetReportNumByTaskId(arg1:number):Promise<string>;

export function GetSiegeSummary():Promise<string>;

export function GetSyncStatus():Promise<string>;

export function GetTask(arg1:number):Promise<string>;

export function GetTaskList():Promise<string>;

export function GetTeamCounter(arg1:number,arg2:number,arg3:number,arg4:number):Promise<string>;

export function GetTeamGroup():Promise<string>;

export function GetTeamUser(arg1:string):Promise<string>;

export function GetTeamWinRate(arg1:string,arg2:string,arg3:number,arg4:number,arg5:number,arg6:number):Promise<string>;

export function GetTeamWinRateByTeam(arg1:string,arg2:string,arg3:number,arg4:number,arg5:number,arg6:number):Promise<string>;

export function GetUnionMemberTopTeams(arg1:number,arg2:number,arg3:number):Promise<string>;

export function GetVersion():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function ImportDb(arg1:string,arg2:Array<number>):Promise<string>;

export function SelectDb(arg1:string):Promise<string>;

export function SetAiThinking(arg1:boolean):Promise<string>;

export function StartAutoScroll(arg1:number,arg2:number,arg3:number,arg4:number):Promise<string>;

export function StatisticsReport(arg1:number):Promise<string>;

export function StopAutoScroll():Promise<string>;

export function TestDirectFetch():Promise<string>;
