// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckNpcap():Promise<string>;

export function CheckUpdate():Promise<string>;

export function CreateDb(arg1:string):Promise<string>;

export function CreateTask(arg1:string,arg2:number,arg3:Array<string>,arg4:Array<string>):Promise<string>;

export function DeleteTask(arg1:number):Promise<string>;

export function DeleteTaskReport(arg1:number):Promise<string>;

export function DisableAutoListen():Promise<string>;

export function DisableBattleCall():Promise<string>;

export function DisableBookData():Promise<string>;

export function DisableEnemyMonitor():Promise<string>;

export function DisableGetBattleReport():Promise<string>;

export function DisableGetReport():Promise<string>;

export function EnableAutoListen():Promise<string>;

export function EnableBattleCall():Promise<string>;

export function EnableBookData():Promise<string>;

export function EnableEnemyMonitor():Promise<string>;

export function EnableGetBattleReport():Promise<string>;

export function EnableGetReport(arg1:number,arg2:number):Promise<string>;

export function ExportTaskReport(arg1:number):Promise<string>;

export function GetBattleReports(arg1:string,arg2:number,arg3:number,arg4:number):Promise<string>;

export function GetDashboardStats():Promise<string>;

export function GetDbList():Promise<string>;

export function GetGroupWu():Promise<string>;

export function GetHotRank():Promise<string>;

export function GetLogs():Promise<string>;

export function GetMemberActivity():Promise<string>;

export function GetPlayerTeam(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number):Promise<string>;

export function GetReportNumByTaskId(arg1:number):Promise<string>;

export function GetTask(arg1:number):Promise<string>;

export function GetTaskList():Promise<string>;

export function GetTeamCounter(arg1:number,arg2:number,arg3:number,arg4:number):Promise<string>;

export function GetTeamGroup():Promise<string>;

export function GetTeamUser(arg1:string):Promise<string>;

export function GetTeamWinRate(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number,arg6:number,arg7:number):Promise<string>;

export function GetTeamWinRateByTeam(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number,arg6:number,arg7:number):Promise<string>;

export function GetVersion():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function SelectDb(arg1:string):Promise<string>;

export function StartAutoScroll(arg1:number):Promise<string>;

export function StatisticsReport(arg1:number):Promise<string>;

export function StopAutoScroll():Promise<string>;
